apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dns
  description: DNS Configuration for domains managed by CDS
spec:
  type: service
  lifecycle: experimental
  owner: group:cds-snc/internal-sre
  domain: site-reliability-engineering
  system: cds-alm
