name: Backstage Catalog Info Helper
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-catalog-info:
    runs-on: ubuntu-latest
    steps:
      - name: Update catalog-info.yaml
        uses: cds-snc/backstage-catalog-info-helper-action@v0.2.0
        with:
          github-app-id: ${{ secrets.SRE_BOT_RW_APP_ID }}
          github-app-private-key: ${{ secrets.SRE_BOT_RW_APP_PRIVATE_KEY }}
          github-organization: ${{ github.repository_owner}}